---
title: "Reproducible Research"
output:
  pdf_document: default
  html_document:
    keep_md: yes
---

## Loading necessary packages
```{r}
library(dplyr)
library(readr)
library(ggplot2)
```

## Loading and preprocessing the data
```{r}
data_path <- list.files(pattern = "activity.csv", 
                        recursive = TRUE, 
                        ignore.case = TRUE)
data <- read_csv(data_path)
```

## What is mean total number of steps taken per day?
```{r}
total_steps <- data %>%
  group_by(date) %>%
  summarise(Total_steps = sum(steps))

hist(total_steps$Total_steps, xlab = "Total steps", main = "Total number of steps taken per day")

mean_total_steps <- mean(total_steps$Total_steps, na.rm = TRUE)
mean_total_steps
median_total_steps <- median(total_steps$Total_steps, na.rm = TRUE)
median_total_steps
```


## What is the average daily activity pattern?
```{r}
mean_steps <- data %>%
  group_by(interval) %>%
  summarise(Number_of_steps = mean(steps, na.rm = TRUE))
  
g <- ggplot(mean_steps, aes(x = interval, y = Number_of_steps)) 
g + geom_line() + xlab("Interval") + ylab("Number of steps") + ggtitle("Average daily activity")

#interval with maximum mean steps 
max_mean_steps <- mean_steps %>%
  filter(Number_of_steps == max(Number_of_steps))
max_mean_steps
```

## Imputing missing values
```{r}
#total number of missing values
NA_count <- sum(is.na(data))
NA_count

#filling missing values by mean steps for the interval
data_wo_NA <- data %>%
  merge(mean_steps, by = "interval") %>%
  mutate(steps_wo_NA = if_else(is.na(steps) == TRUE, Number_of_steps, steps))
head(data_wo_NA, 10)

total_steps_wo_NA <- data_wo_NA %>%
  group_by(date) %>%
  summarise(Total_steps = sum(steps_wo_NA))

hist(total_steps_wo_NA$Total_steps, xlab = "Total steps", main = "Total number of steps taken per day wo NA")

#mean and median of the data without missing values 
mean_total_steps_wo_NA <- mean(total_steps_wo_NA$Total_steps)
mean_total_steps_wo_NA
median_total_steps_wo_NA <- median(total_steps_wo_NA$Total_steps)
median_total_steps_wo_NA

#absolute differences
abs(mean_total_steps - mean_total_steps_wo_NA)
abs(median_total_steps - median_total_steps_wo_NA)
```

## Are there differences in activity patterns between weekdays and weekends?
```{r}
mean_steps_wo_NA <- data_wo_NA %>%
  group_by(interval, weekend_t = chron::is.weekend(date)) %>%
  summarise(Number_of_steps = mean(steps_wo_NA)) %>%
  mutate(weekend_v = if_else(weekend_t == TRUE, "weekend", "weekday"))

g <- ggplot(mean_steps_wo_NA, aes(interval, Number_of_steps))
g + geom_line() + facet_grid(.~ weekend_v) + xlab("Interval") + ylab("Number of steps") + 
  ggtitle("Total number of steps taken per day without missing values in the weekday and weekend day")
```